import re
from typing import Callable


def generator_numbers(text: str):
    """Generate real numbers from the text."""
    # Regular expression to find real numbers separated by spaces
    pattern = r'\b\d+\.\d+\b'
    # Find all matches in the text
    matches = re.findall(pattern, text)
    # Yield each match as a float number
    for match in matches:
        yield float(match)


def sum_profit(text: str, func: Callable):
    """Sum up the total profit from the text using a given generator function."""
    # Initialize total sum
    total_sum = 0
    # Iterate over numbers generated by the provided function
    for number in func(text):
        # Add each number to the total sum
        total_sum += number
    return total_sum


# Example usage
text = "Загальний дохід працівника складається з декількох частин: 1000.01 як основний дохід, доповнений додатковими надходженнями 27.45 і 324.00 доларів."
total_income = sum_profit(text, generator_numbers)
print(f"Загальний дохід: {total_income}")
